// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getConfigByUserID = `-- name: GetConfigByUserID :one
SELECT id, user_id, chat_id
FROM forward_config
WHERE user_id = ?
`

func (q *Queries) GetConfigByUserID(ctx context.Context, userID int64) (ForwardConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfigByUserID, userID)
	var i ForwardConfig
	err := row.Scan(&i.ID, &i.UserID, &i.ChatID)
	return i, err
}

const saveConfig = `-- name: SaveConfig :exec
INSERT INTO forward_config (user_id, chat_id)
VALUES (?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    chat_id = excluded.chat_id
`

type SaveConfigParams struct {
	UserID int64
	ChatID int64
}

func (q *Queries) SaveConfig(ctx context.Context, arg SaveConfigParams) error {
	_, err := q.db.ExecContext(ctx, saveConfig, arg.UserID, arg.ChatID)
	return err
}
